Simple_blog/urls.py
from django.contrib import admin
from django.conf import settings			# imports for
from django.conf.urls.static import static	# static
from django.conf.urls import url, include

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^create/$', views.CreateView.as_view(), name='create'),
	url(r'^(?P<slug>[\w-]+)/edit/$', views.UpdateView.as_view(), name='edit'),
	url(r'^(?P<slug>[\w-]+)/delete/$', views.delete, name='delete'),
	url(r'^(?P<slug>[\w-]+)/$', views.detail, name='detail'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="{% static 'css/master.css' %}">

    
  <!-- VK scripts -->

  <!-- /VK scripts -->


</head>
<body>
  <!-- Messages -->
  {% include 'messages_display.html' %}
  <!-- /Messages -->
  
  <!-- Main content -->
  <main>
  {% block content %}

  {% endblock content %}
  </main>
  <!-- /Main content -->
  
  <!-- Scripts -->
  
</body>
</html>

templates/detail.html
{% extends "base.html" %}
<!-- String below adds custom function -->
<!-- For templates from templatetags -->
{% load urlify %}
{% block title %}
  {{ post.title }}
{% endblock title %}

{% block content %}
  <!-- Timestamp -->
  {% if post.late_publish and post.late_publish > actual_datetime %}
  	<!-- Stuff showing message -->
    <p class="drafted-message">Post is in draft</p>
    <!-- /Stuff showing message -->
  	<small>{{ post.late_publish }}</small>
  {% else %}
  	<small>{{ post.timestamp }}</small>
  {% endif %}
  <!-- /Timestamp -->
  <h1>Detail page</h1>
  <h2>{{ post.title }}</h2>
  {% if post.image %}
  	<img src="{{ post.image.url }}" alt="{{ post.image.title }}">
  {% endif %}
  <p>{{ post.content }}</p>
  <!-- VK like block -->
  
  <!-- /VK like block -->
  
  <!-- Social share Links -->
  <a href="http://vk.com/share.php?url={{ request.build_absolute_uri }}&title={{ post.title|urlify }}&description={{ post.content|truncatewords:30|urlify }}" target="_blank">
    Поделиться Вконтактике
  </a><br>
  <!-- /Social share Links -->
  
  {% if post.user.get_full_name %}
    <p>Автор: {{ post.user.get_full_name }}</p>
  {% endif %}
  
  <a href="{% url 'blog:home' %}">To the home page</a>
  
  
  <!-- VK comments block -->

  <!-- /VK comments block -->

{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
<!-- Search bar -->
<form method="GET" action="">
  <input type="search" name="q" placeholder="Search" value="{{ request.GET.q }}"/>
  <input type="submit" value="search">
</form>
<!-- /Search bar -->
<h1>{{ title }}</h1>
<!-- ADD HERE NOTATION IF THERE ARE NO RESULT FOR THE SEARCH -->
{% for post in post_list %}
  <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
  <p>{{ post.content|truncatewords:20 }}</p>
  <!-- Timestamp -->
  {% if post.late_publish and post.late_publish > actual_datetime %}
  	<!-- Stuff showing message -->
    <p class="drafted-message">Post is in draft</p>
    <!-- /Stuff showing message -->
  	<small>{{ post.late_publish }}</small>
  {% else %}
  	<small>{{ post.timestamp }}</small>
  {% endif %}
  <!-- /Timestamp -->
  {% if post.user.get_full_name %}
    <p>Автор: {{ post.user.get_full_name }}</p>
  {% endif %}
{% endfor %}

<!-- I add advanced pagination -->
<!-- So search will be correct in all pages-->
<div class="pagination">
    <span class="step-links">
        {% if post_list.has_previous %}
            <a href="?page={{ post_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ post_list.number }} of {{ post_list.paginator.num_pages }}.
        </span>
		
        {% if post_list.has_next %}
            <a href="?page={{ post_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>
{% endblock content %}

templates/messages_display.html
{% if messages %}
  <div class="messages-block">
    <ul class="messages">
        {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
  </div>
{% endif %}

templates/post_form.html
{% extends "base.html" %}
{% block title %}Create/Edit post{% endblock title %}
{% block content %}
  <h1>Create/Edit post</h1>
  <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value='create'>
  </form>
{% endblock content %}